### ISSUE TITLE
asl script seem to be broken

### ISSUE THREAD

**Issue by drmalc** [LiveSplit/LiveSplit.ScriptableAutoSplit#5]
Hi, I hope this is not a pebkac but autosplit script seem to be broken. Here is a simple script that works (the test.txt file is created, the timer starts immediately):

    state("BorderlandsPreSequel")
    {
        
    }
    start
    {
        System.IO.File.WriteAllText(@"C:\temp\test.txt", "hi");
        return true;
    }

And a similar one that doesn't:

    state("BorderlandsPreSequel")
    {
        bool fubar : "BorderlandsPreSequel.exe", 0x1C6C0D0;
    }
    start
    {
        System.IO.File.WriteAllText(@"C:\temp\test.txt", "hi");
        return true;
    }

Even with an address that I know is valid, the txt file isn't created and the timer doesn't start. I have two asl that used to work in the previous version. Let me know if you need something, although I don't have a proper csharp toolchain installed.

**Comment by CryZe** [comment]
Yeah, somehow the last update killed it even though this is all that got changed: https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/compare/1.1...1.1.1

**Comment by drmalc** [comment]
The timer starts with this code:

    bool fubar : "BorderlandsPreSequel.exe", 0x1C6C0D0, 0x0;

I only added ", 0x0" at the end.

**Comment by CryZe** [comment]
Turns out the new Roslyn compiler of Visual Studio 2015 has a few bugs or something and that's why it doesn't work anymore. Compiling it with Visual Studio 2013 fixes it.
