### ISSUE TITLE
Uncheck All button only unchecks top-level settings

### ISSUE THREAD

**Issue by Gyoshi** [LiveSplit/LiveSplit.ScriptableAutoSplit#58]
I feel like it should do what it actually says and uncheck all the settings, not just deactivate them via parents. Are there people with strong opinions to the contrary?

I wanted to use it to build up splits from a blank slate, but if everything is hierarchical, there is no simple way of just clearing it all (unless the defaults were all false).

I'm vaguely sure it's as simple as removing one if statement, so I'll go ahead and make a pull request

**Comment by wooferzfg** [comment]
It's supposed to update recursively, yeah: https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/master/ComponentSettings.cs#L345

**Comment by Gyoshi** [comment]
Yeah ok I don't actually see how it doesn't work. `UpdateNodesCheckedState` is using `UpdateNodesInTree`, which does:
https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/9551e176e987daea95eaa34a8580afa6ae56962d/ComponentSettings.cs#L308-L309
and the `Func` in question always returns `true`, so all nodes should be accessed. Pretty straight-forward.

Could it be related to the (supposedly GUI only) disabling of checkboxes with disabled parents? https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/pull/46

**Comment by wooferzfg** [comment]
Yeah, that seems like what's causing the issue.

**Comment by Gyoshi** [comment]
I was looking into moving it to the NodeMouseClick event handler, but that handles node selection as well, not just checking.
